
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Sep 19 00:08:56 COT 2021
//----------------------------------------------------

package SoloLexico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_relacional = 21;
  public static final int Coma = 34;
  public static final int Llave_c = 28;
  public static final int Op_booleano = 24;
  public static final int Unsigned = 41;
  public static final int Llave_a = 27;
  public static final int If = 6;
  public static final int T_dato = 4;
  public static final int Else = 7;
  public static final int Cout = 38;
  public static final int Corchete_c = 30;
  public static final int Doble = 14;
  public static final int Corchete_a = 29;
  public static final int Punto = 33;
  public static final int Parent_c = 26;
  public static final int Parent_a = 25;
  public static final int While = 11;
  public static final int Division = 19;
  public static final int Int = 13;
  public static final int Cadena = 5;
  public static final int For = 12;
  public static final int EOF = 0;
  public static final int P_coma = 32;
  public static final int Printf = 35;
  public static final int error = 1;
  public static final int Switch = 8;
  public static final int Linea = 2;
  public static final int Op_atribucion = 22;
  public static final int ERROR = 47;
  public static final int Do = 10;
  public static final int Op_logico = 20;
  public static final int Case = 9;
  public static final int Short = 40;
  public static final int Scanf = 36;
  public static final int Const = 39;
  public static final int Identificador = 45;
  public static final int Struct = 42;
  public static final int Cin = 37;
  public static final int Resta = 17;
  public static final int Typedef = 43;
  public static final int Palabra_Reservada = 44;
  public static final int Multiplicacion = 18;
  public static final int Op_incremento = 23;
  public static final int Numero = 46;
  public static final int Suma = 16;
  public static final int Main = 31;
  public static final int Igual = 15;
  public static final int Comillas = 3;
}

