
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Sep 23 23:03:34 COT 2021
//----------------------------------------------------

package SoloLexico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_relacional = 27;
  public static final int Coma = 47;
  public static final int Llave_c = 40;
  public static final int Op_booleano = 30;
  public static final int Unsigned = 54;
  public static final int Llave_a = 39;
  public static final int If = 6;
  public static final int T_dato = 4;
  public static final int Default = 11;
  public static final int Else = 7;
  public static final int Cout = 51;
  public static final int Enum = 38;
  public static final int Break = 10;
  public static final int Goto = 34;
  public static final int Corchete_c = 42;
  public static final int Doble = 17;
  public static final int Corchete_a = 41;
  public static final int Extern = 36;
  public static final int Union = 35;
  public static final int Long = 19;
  public static final int Punto = 46;
  public static final int Parent_c = 32;
  public static final int Return = 12;
  public static final int Parent_a = 31;
  public static final int While = 14;
  public static final int Division = 25;
  public static final int Int = 16;
  public static final int Cadena = 5;
  public static final int Float = 18;
  public static final int For = 15;
  public static final int P_coma = 45;
  public static final int EOF = 0;
  public static final int DosPuntos = 44;
  public static final int Printf = 48;
  public static final int error = 1;
  public static final int Switch = 8;
  public static final int Linea = 2;
  public static final int Char = 20;
  public static final int Op_atribucion = 28;
  public static final int ERROR = 60;
  public static final int Do = 13;
  public static final int Continue = 33;
  public static final int Op_logico = 26;
  public static final int Case = 9;
  public static final int Short = 53;
  public static final int Register = 37;
  public static final int Scanf = 49;
  public static final int Const = 52;
  public static final int Identificador = 58;
  public static final int Struct = 55;
  public static final int Cin = 50;
  public static final int Resta = 23;
  public static final int Typedef = 56;
  public static final int Palabra_Reservada = 57;
  public static final int Multiplicacion = 24;
  public static final int Op_incremento = 29;
  public static final int Numero = 59;
  public static final int Suma = 22;
  public static final int Main = 43;
  public static final int Igual = 21;
  public static final int Comillas = 3;
}

