package SoloLexico;

public enum Tokens {
    Int,
    Doble,
    Linea,
    Comillas,
    T_dato,
    Cadena,
    //----------------------------------
    If,
    Else,
    Switch,
    Case,
    Break,
    Default,
    Return,
    //---------------------------------
    Do,
    While,
    For,
    //-------------------------------------------------
    Igual,
    Suma,
    Resta,
    Multiplicacion,
    Division,
    //-------------------------------------------------
    Op_logico,
    Op_incremento,
    Op_relacional,
    Op_atribucion,
    Op_booleano,
    Parent_a,
    Parent_c,
    Llave_a,
    Llave_c,
    Corchete_a,
    Corchete_c,
    Punto,
    Coma,
    P_Coma,
    DosPuntos,
    //---------------------------------------------
    Palabra_Reservada,
    Main,
    //---------------------------------------------
    Printf,
    Scanf,
    Cin,
    Cout,
    //----------------------------------------------
    Const,
    Short,
    Unsigned,
    Struct,
    Typedef,
    //----------------------------------------------
    Identificador,
    Numero,
    ERROR
}
